[package]
name = "noir_swift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.11"

[dependencies]
swift-bridge = "0.1"
noir_rs = { git = "https://github.com/visoftsolutions/noir_rs.git" }